shared_buffers = 128MB
work_mem = 4MB
maintenance_work_mem = 32MB
effective_cache_size = 512MB
huge_pages = off
max_connections = 20

wal_level = minimal
max_wal_senders = 0
wal_compression = zstd
synchronous_commit = on
commit_delay = 0
wal_buffers = 12MB
max_wal_size = 256MB
min_wal_size = 64MB
checkpoint_timeout = 15min
checkpoint_completion_target = 0.9

autovacuum_max_workers = 2
autovacuum_naptime = 1min
autovacuum_vacuum_cost_delay = 20ms
autovacuum_vacuum_cost_limit = 200

random_page_cost = 2.0
effective_io_concurrency = 1

log_destination = 'stderr'
logging_collector = off
log_min_messages = warning
log_min_error_statement = error

listen_addresses = 'localhost'
port = 5432
unix_socket_directories = '/var/run/postgresql'

lc_messages = 'C'
lc_monetary = 'C'
lc_numeric = 'C'
lc_time = 'C'
